greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking cafe Cereza

droid:
  id: BB-8
  description: Small, rolling android. Probably doesn't drink coffee.

management:
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: '*'
